name: DL
channels:
  - pytorch
dependencies:
  - python
  - pytorch==1.5.0
  - numpy
  - scikit-learn
  - pandas
  - pip
  - matplotlib
  - pip
  - pip:
    - shapely
    - pillow==7.0.0
    - torchvision==0.5.0
    - tqdm
