name: DL
channels:
  - pytorch
dependencies:
  - python
  - pytorch
  - torchvision==0.4.2
  - numpy
  - scikit-learn
  - pandas
  - pip
  - matplotlib
  - pip
    - pip:
    - shapely
    - pillow==6.1
    - tqdm
